namespace CompilerCore
{
    /// <summary>
    /// Instances of this class are generated by Scanner.
    /// </summary>
    internal class Token : IToken
    {
        public string Lexeme { get; private set; }
        public int Line { get; private set; } // the line number (one-based) where the lexeme was encountered
        public TokenType Type { get; private set; }

        internal Token(string lexeme, int line)
        {
            Lexeme = lexeme;
            Line = line;
            Type = Utils.DetermineTokenTypeFrom(lexeme);
        }
    }
}
